#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	post_customization
# called by:	uic_create, uic_build, uic_upgrade
#
# This hook will be called by several commands after making any customizations
# (file copies and deletions) to the installation environment in $TARGET


# copy the configuration file to the destination file system but remove the array
# definitions since they are not compatible with /bin/sh
sed -e "s/^UIC_TARGET.*/# DELETEME/g" <  "${TARGET}/uictpl.conf" | grep -v "^# DELETEME" > "${TARGET}/chroot/etc/uictpl.conf"

# add some more information
echo "UIC_CREATION_TIMESTAMP=\"$(date +'%Y-%m-%d %H:%M %z')\"" >> "${TARGET}/chroot/etc/uictpl.conf"
echo "UIC_CREATION_VERSION=\"${VERSION}\"" >> "${TARGET}/chroot/etc/uictpl.conf"

# rewrite the /etc/motd.tail
echo > "${TARGET}/chroot/etc/motd.tail"
echo "Welcome to YeaSoft NetPoldo Ubuntu ${UIC_SRCVERSION} Rescue System!" >> "${TARGET}/chroot/etc/motd.tail"
echo >> "${TARGET}/chroot/etc/motd.tail"
echo "Created from Ubuntu (${UIC_RELEASE}) on $(date +'%Y-%m-%d %H:%M %z') using" >> "${TARGET}/chroot/etc/motd.tail"
echo " - UIC (Ubuntu Installation Creator) ${VERSION}" >> "${TARGET}/chroot/etc/motd.tail"
echo " - ${UIC_SRCNAME} ${UIC_SRCVERSION} uic template" >> "${TARGET}/chroot/etc/motd.tail"
echo >> "${TARGET}/chroot/etc/motd.tail"
echo " * Documentation: http://www.yeasoft.com/netpoldo" >> "${TARGET}/chroot/etc/motd.tail"
echo "                  http://www.ubuntu.com/server" >> "${TARGET}/chroot/etc/motd.tail"
echo >> "${TARGET}/chroot/etc/motd.tail"
