#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	pre_build
# called by:	uic_build
#
# This hook will be called by uic_build before performing the first build
# step of the build procedure in the installation environment in $TARGET
#!/bin/sh


(
cat <<EOF

Welcome to YeaSoft's Alix Ubuntu ${UIC_SRCVERSION} Rescue System!

Created from Ubuntu (${UIC_RELEASE}) on $(date +'%Y-%m-%d %H:%M %z') using
 - UIC (Ubuntu Installation Creator) ${VERSION}
 - ${UIC_SRCNAME} ${UIC_SRCVERSION} uic template

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To access official Ubuntu documentation, please visit:
http://help.ubuntu.com/

EOF
) > "$TARGET/chroot/etc/motd.tail"
