#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs hook prepares the initial ramdisk for the
# yeasoft extended boot system
#
# Version: 20130314
# Compatibility: wheezy(i386,amd64) squeeze(i386,amd64), precise(i386,amd64), lucidi386,amd64), hardyi386,amd64)

PREREQS=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQS"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/lib/udev
if [ -e /lib/udev/rules.d/60-cdrom_id.rules ]; then
	mkdir -p ${DESTDIR}/lib/udev/rules.d
	cp -p /lib/udev/rules.d/60-cdrom_id.rules ${DESTDIR}/lib/udev/rules.d/
fi
[ -e /lib/udev/cdrom_id ] && copy_exec /lib/udev/cdrom_id /lib/udev
[ -e /lib/udev/vol_id ] && copy_exec /lib/udev/vol_id /lib/udev
[ -e /lib/udev/path_id ] && copy_exec /lib/udev/path_id /lib/udev

# squashfs
manual_add_modules squashfs
manual_add_modules loop

# random file system modules
manual_add_modules vfat
manual_add_modules ext3
manual_add_modules ext4
# needed for vfat. :-/
manual_add_modules nls_cp437
manual_add_modules nls_utf8
manual_add_modules nls_iso8859-1

# cdrom modules
manual_add_modules sr_mod
manual_add_modules ide-cd
manual_add_modules sbp2
manual_add_modules ohci1394

# auto_add_modules net
