#!/bin/bash
#
# (c) 2012-2013 YeaSoft Int'l - Leo Moll
#
# uic hook:	post_installation
# called by:	uic_create, uic_upgrade
#
# This hook will be called by uic_create after making all software
# installation and configuration steps in the installation environment
# in $TARGET

# remove the bootbank preseed file
if [ -e "${TARGET}/chroot/etc/default/bootbank-preseed" ]; then
	rm -f "${TARGET}/chroot/etc/default/bootbank-preseed"
fi

# if the bootbank was mounted read only by the installing system
# let clean the mess up...
BOOTBANK_LABEL=bootbank
BOOTBANK_MOUNT=
domakerw=0

if [ -e "${TARGET}/chroot/etc/default/uictemp" ]; then
	. "${TARGET}/chroot/etc/default/uictemp"
fi

if [ $domakerw -eq 1 ]; then
	show_verbose  1 "Remounting bootbank device in read only mode..."
	mount -o remount,ro ${BOOTBANK_MOUNT}
	rm -f "${TARGET}/chroot/etc/default/uictemp"
fi

# the installation sometimes overwrites files without asking
# so we should reapply all customizations
apply_customizations
