#!/bin/bash
#
# (c) 2012-2014 YeaSoft Int'l - Leo Moll
#
# uic chroot hook:      chroot_post_installation
# called by:            uic_create, uic_upgrade
#
# This hook will be called by uic_create in the chrooted installation
# environment in $TARGET after making all software installation and
# configuration steps. Since this hook runs in chroot, none of the
# internal UIC variables are available.

# INSTALL EXTLINUX MANUALLY
# we need the extlinux binary but unfortunately it is not included
# any more in syslinux. The package extlinux does not only contain
# the binary but also a collection of scripts AND hooks for installing
# and updating the boot manager every time the kernel is updated or
# changed.

tempdir=$(mktemp -d)
pushd $tempdir
apt-get install -d extlinux
dpkg -x /var/cache/apt/archives/extlinux_*.deb .
if [ -f usr/bin/extlinux ]; then
        cp -a usr/bin/extlinux /usr/bin
elif [ -f usr/sbin/extlinux ]; then
	cp -a usr/sbin/extlinux /usr/sbin
fi
cp -a usr/share/man/man1/extlinux.1.gz /usr/share/man/man1/extlinux.1.gz
popd
rm -rf $tempdir
