#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for a loop filesystem
# in local rootfs environments.
# This part is executed at the BEGIN of the "init" script sequence
#
# Version: 20120510
# Compatibility: squeeze(i386,amd64)

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

[ "$quiet" != "y" ] && log_begin_msg "Parsing LOOP specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	loop=*)
		LOOP="${x#loop=}"
	        echo "LOOP=\"${LOOP}\"" >> /conf/param.conf
		;;
	loopflags=*)
		LOOPFLAGS="-o ${x#loopflags=}"
	        echo "LOOPFLAGS=\"${LOOPFLAGS}\"" >> /conf/param.conf
		;;
	loopfstype=*)
		LOOPFSTYPE="${x#loopfstype=}"
	        echo "LOOPFSTYPE=\"${LOOPFSTYPE}\"" >> /conf/param.conf
		;;
	esac
done
[ "$quiet" != "y" ] && log_end_msg
