#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for configuring
# the dhcp server interface from the kernel comandline.

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

DHCPDIFIP=
DHCPDIFMASK=
DHCPDIFENABLE=

valid_dotted_quad() {
	ERROR=0
	oldIFS=$IFS
	IFS=.
	set -f
	set -- $1
	if [ $# -eq 4 ]; then
		ELEMENT=0
		for seg; do
			ELEMENT=$(( ELEMENT + 1 ))
			case $seg in
			""|*[!0-9]*) ERROR=1;break ;; ## Segment empty or non-numeric char
			*) [ $seg -gt 255 ] && ERROR=2 ;;
			esac
			case $ELEMENT in
			1) DHCPDIFNET=$seg;;
			2) DHCPDIFNET=${DHCPDIFNET}.${seg};;
			3) DHCPDIFNET=${DHCPDIFNET}.${seg};;
			esac
		done
	else
		ERROR=3 ## Not 4 segments
	fi
	IFS=$oldIFS
	set +f
	return $ERROR
}

log_begin_msg "Parsing DHCPD overlay specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	dhcpdif-mask=*)
		DHCPDIFMASK=${x#dhcpdif-mask=}
		;;
	dhcpdif-ip=*)
		DHCPDIFIP=${x#dhcpdif-ip=}
		;;
	dhcpdif-en*)
		DHCPDIFENABLE="YES"
		;;
	esac
done
log_end_msg

if [ "${DHCPDIFMASK}" != "" ]; then
	DHCPDIFNET=
	if valid_dotted_quad "${DHCPDIFMASK}"; then
		[ "$quiet" != "y" ] && log_begin_msg "Setting netmask of primary DHCP interface to ${DHCPDIFMASK}..."
		sed -e "s/255.255.255.000/${DHCPDIFMASK}/g" < ${rootmnt}/etc/network/interfaces > /tempfile
		mv /tempfile ${rootmnt}/etc/network/interfaces
		sed -e "s/255.255.255.000/${DHCPDIFMASK}/g" < ${rootmnt}/etc/dhcp3/dhcpd.conf > /tempfile
		mv /tempfile ${rootmnt}/etc/dhcp3/dhcpd.conf
		[ "$quiet" != "y" ] && log_end_msg
	fi
fi

if [ "${DHCPDIFIP}" != "" ]; then
	DHCPDIFNET=
	if valid_dotted_quad "${DHCPDIFIP}"; then
		[ "$quiet" != "y" ] && log_begin_msg "Setting ip address of primary DHCP interface to ${DHCPDIFIP}..."
		sed -e "s/192.168.1.1/${DHCPDIFIP}/g"  < ${rootmnt}/etc/network/interfaces > /tempfile
		mv /tempfile ${rootmnt}/etc/network/interfaces
		sed -e "s/192.168.1.1/${DHCPDIFIP}/g"  < ${rootmnt}/etc/dhcp3/dhcpd.conf > /tempfile
		mv /tempfile ${rootmnt}/etc/dhcp3/dhcpd.conf
		sed -e "s/192.168.1./${DHCPDIFNET}./g" < ${rootmnt}/etc/dhcp3/dhcpd.conf > /tempfile
		mv /tempfile ${rootmnt}/etc/dhcp3/dhcpd.conf
		[ "$quiet" != "y" ] && log_end_msg
	fi
fi

if [ "${DHCPDIFENABLE}" != "" ]; then
	[ "$quiet" != "y" ] && log_begin_msg "Enabling DHCP server on primary DHCP interface..."
	sed -e "s/\"eth1\"/\"eth0 eth1\"/g" < ${rootmnt}/etc/default/dhcp3-server > /tempfile
	mv /tempfile ${rootmnt}/etc/default/dhcp3-server
	[ "$quiet" != "y" ] && log_end_msg
fi
