#!/bin/bash

ALIX_DIRS="alix-rescue-deb7 alix-rescue-deb6 alix-rescue-0804 alix-rescue-1004"

for alixdir in $ALIX_DIRS; do
	if [ ! -d alix-rescue/$alixdir ]; then
		echo "ERROR: Script must be lauched from the 'alix/alix-rescue' directory" >&2
		exit 5
	fi
done

function alix_clean {
	for alixdir in $ALIX_DIRS; do
		uic clean ${alixdir}
	done
}

function alix_create {
	for alixdir in $ALIX_DIRS; do
		uic create ${alixdir}
	done
}

function alix_build {
	for alixdir in $ALIX_DIRS; do
		uic build ${alixdir}
	done
}

function alix_pack {
	for alixdir in $ALIX_DIRS; do
		uic pack -o . -v alix-rescue/$alixdir
		source alix-rescue/$alixdir/uictpl.conf
		case "$UIC_RELEASE" in
		"squeeze")
		"wheezy")
			FLAV="debian"
			;;
		*)
			FLAV="ubuntu"
			;;
		esac
		tar czf alix-rescue-${FLAV}-${UIC_SRCVERSION}.tar.gz \
			-C alix-rescue/doc readme.txt relnotes.txt \
			-C ../$alixdir/build syslinux pxelinux.cfg \
			-C ../output package-list.txt axrescue.vmlinuz axrescue.initrd axrescue.initrdn axrescue.squashfs
		touch --reference alix-rescue/$alixdir/output/axrescue.squashfs alix-rescue-${FLAV}-${UIC_SRCVERSION}.tar.gz
	done
}


function alix_upload {
	for alixdir in $ALIX_DIRS; do
		rsync -avc ${alixdir}/output/* 10.65.6.1:/mnt/data/tftproot/yeaboot/${alixdir}/
	done
}

case "$1" in
clean)
	alix_clean
	;;
create)
	alix_create
	;;
build)
	alix_build
	;;
pack)
	alix_pack
	;;
upload)
	alix_upload
	;;
all)
	alix_clean
	alix_create
	alix_build
	alix_pack
	;;
*)
	echo "Usage: make_alix {clean|pack|create|build|upload|all}"
        exit 1
        ;;
esac

exit 0
