#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for setting roots
# password from the kernel comandline.

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

PASSWORD=

log_begin_msg "Parsing overlay specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	password=*)
		PASSWORD=${x#password=}
		SHADOW=${PASSWORD#SHADOW:}
		;;
	esac
done
log_end_msg

if [ "$PASSWORD" != "" ]; then
	if [ "${PASSWORD}" = "${SHADOW}" -o "${SHADOW}" = "" ]; then
		# clear text password specified
		[ "$quiet" != "y" ] && log_begin_msg "Setting root password to specified cleartext value..."
		chroot ${rootmnt} echo -e "${PASSWORD}\n${PASSWORD}" | chroot ${rootmnt} passwd root
		[ "$quiet" != "y" ] && log_end_msg
	else
		# shadow hash specified
		[ "$quiet" != "y" ] && log_begin_msg "Setting root password to specified shadow hash..."
		sed -e "s/root:[^:]*:/root:$(echo -n ${SHADOW} | sed -e 's/\//\\\//g'):/" < ${rootmnt}/etc/shadow > ${rootmnt}/shadow.tmp
		mv ${rootmnt}/shadow.tmp ${rootmnt}/etc/shadow
		[ "$quiet" != "y" ] && log_end_msg
	fi
fi
